ДЗ 1
Bertruchio/2024-2-VK-EDU-Frontend-A-Plaksin pull request #1
Opened 2024-09-20 20:05 UTC by Bertruchio

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @1marbur1 проверить его.

Что было сделано:
* Собрал новый проект
* Реализовал три функции: конвертации байт, поиска неуникальных элементов, проверки предложений
* Написал тесты на функцию конвертации байт

2024-09-20 22:17 UTC, 1MarBur1 requested changes

2024-09-20 22:17 UTC, 1MarBur1 commented on my-project/convertBytesToHuman.js
> +  if (typeof bytes !== 'number' || bytes < 0) {
что будет если передать аргументом NaN, Infinity?

2024-09-20 22:17 UTC, 1MarBur1 commented on my-project/convertBytesToHuman.js
> +  const result = bytes.toFixed(2).replace(/\.?0+$/, '');
можно использовать просто +bytes.toFixed(2), либо parseFloat()

2024-09-20 22:17 UTC, 1MarBur1 commented on my-project/correctSentence.js
> +  return firstLetterCapitalized.endsWith('.') ? firstLetterCapitalized : firstLetterCapitalized + '.';
все работает как нужно, но код выглядит не совсем чистым

давай всю работу со строкой будем делать в одном месте. сейчас же получается - сначала заменяем первую букву на заглавную, записываем в переменную, только потом выводим

может быть вообще не будем задействовать лишнюю память?

2024-09-21 06:19 UTC, Bertruchio commented on my-project/convertBytesToHuman.js
> +  if (typeof bytes !== 'number' || bytes < 0) {
Всё плохо... 
При Infinity программа войдёт в бесконечный цикл. 
А при NaN условие не выполнится, и, в выводе окажется либо "NaN B", либо ошибка TypeError.

Забыл добавить проверку.

2024-09-21 06:23 UTC, Bertruchio commented on my-project/convertBytesToHuman.js
> +  const result = parseFloat(bytes.toFixed(2));
В исправлении использовал parseFloat(), т.к. показалось, что это наиболее явное преобразование. 
Но часто ли используют "+" на практике? Если, да, то хотел бы использовать именно его.

2024-09-21 08:33 UTC, 1MarBur1 requested changes

2024-09-21 08:33 UTC, 1MarBur1 commented on my-project/convertBytesToHuman.js
> +  const result = parseFloat(bytes.toFixed(2));
Да, вполне часто используют именно "+".  

Вообще .toFixed() возвращает нам строку, наша же задача - перевести ее в валидное число. Сам по себе number не может быть вида 1.10, только 1.1 (он сам откинет ненужные нули)

Поэтому здесь мы можем использовать даже просто Number(), альтернативой которого как раз является "+") Это более быстрая и емкая запись)

2024-09-21 08:33 UTC, 1MarBur1 commented on my-project/correctSentence.js
> +  return text.charAt(0).toUpperCase() + text.slice(1).replace(/[^.]$/, '$&.');
Мы не хотим использовать replace, поскольку так мы будем переберать все возможно подходящие нам элементы

Тут мы точно знаем с каким символом хотим провести работу, а именно .at(-1)

Давай не будем усложнять)

2024-09-22 16:09 UTC, 1MarBur1 approved these changes
@martinkomitsky @HaseProgram @kgrechin approved

2024-09-22 16:39 UTC, kgrechin requested changes
от меня пару вопросов, фиксить ничего не надо

пожалуйста отпиши свое мнение насчет каждого

2024-09-22 16:39 UTC, kgrechin commented on my-project/convertBytesToHuman.js
> +  while (bytes >= 1024 && index < units.length - 1) {
@Bertruchio почему именно циклом while решил сделать? как думаешь возможно ли через цикл for сделать? или мб еще какие-то варианты решения приходят на ум?

2024-09-22 16:39 UTC, kgrechin commented on my-project/correctSentence.js
> +  return text.charAt(0).toUpperCase() + text.slice(1) + (text.at(-1) === '.' ? '' : '.');;
как думаешь нужна ли проверка входного значения в данной функции? если да, то какая?

2024-09-22 16:39 UTC, kgrechin commented on my-project/nonUniqueElements.js
> +  return data.filter(item => data.indexOf(item) !== data.lastIndexOf(item));
тут у нас небольшие тестовые данные, а представь если бы были массивы из тысячи символов, у методы indexOf и lastIndexOf - time complexity o(n). хорошо ли их использовать внутри цикла? мб есть идеи как это улучшить?

2024-09-22 16:42 UTC, kgrechin approved these changes

2024-09-22 17:27 UTC, Bertruchio commented on my-project/convertBytesToHuman.js
> +  while (bytes >= 1024 && index < units.length - 1) {
Т.к. переменная index была нужна снаружи области видимости цикла (для вывода), подумал именно про while (возможно, её стоило назвать как-то иначе). Написать через for тоже можно, но в данном случае он не дает значительных преимуществ, поскольку нам не нужно заранее знать количество итераций. Да, было бы компактнее, но я для меня такой вариант показался нагляднее. Ещё можно было завести отдельную функцию с рекурсией, но при больших значениях может случиться абзац с перегрузом, хотя, по идее, и результат будет выдаваться быстрее. А решать при помощи матана будто бы излишне в контексте данной задачи - *было лень*

2024-09-22 17:42 UTC, Bertruchio commented on my-project/correctSentence.js
> +  return text.charAt(0).toUpperCase() + text.slice(1) + (text.at(-1) === '.' ? '' : '.');;
Проверка того, что предложение уже правильное. Про это я как-то забыл, тут это тоже можно было сделать)

А если начинать думать про модульность, то, тем более. Как минимум, нужны будут проверки на входные данные. Например, что на входе будет именно строка или её не будет вовсе. А ещё на пробелы, на наличие только чисел в строке, спец. символы... Если это будет использовать пользователь (пишет комментарии, например), то нужна проверка на html-элементы, чтобы что-то нехорошее не отправили на сервер. Думаю, много чего ещё упустил

2024-09-22 18:02 UTC, Bertruchio commented on my-project/nonUniqueElements.js
> +  return data.filter(item => data.indexOf(item) !== data.lastIndexOf(item));
В сумме выйдет O(n^2), правильно? С алгоритмами беда, никак не возмусь за них полноценно. Но тут и так понятно, что будет всё очень плохо...))

Помню, что как-то можно решить этот вопрос через нахождение частоты элемента. Тогда прохода будет два: по массиву и объекту. И сложность уже будет хотя бы на уровне O(n).

2024-09-25 20:57 UTC, martinkomitsky approved these changes
12!

2024-09-25 20:57 UTC, merged