ДЗ 2
Bertruchio/2024-2-VK-EDU-Frontend-A-Plaksin pull request #2
Opened 2024-10-03 19:20 UTC by Bertruchio

# Домашнее задание №2

Прошу @martinkomitsky, @haseprogram, @kgrechin или @1marbur1 проверить его.

Что было сделано:
* Реализована функция отправки сообщений в чат.
* Добавлена возможность сохранять сообщения в localStorage.
* Улучшен интерфейс чата, добавлены иконки статуса сообщений.

2024-10-03 19:24 UTC, Bertruchio commented
![Messanger DEMO](https://github.com/user-attachments/assets/41b44d02-1429-48be-94eb-b244c0fc1c05)

2024-10-03 19:41 UTC, Bertruchio commented
Прошу прощения у всех, кто это смотрит. Впервые собираю что-то на action

2024-10-07 21:12 UTC, 1MarBur1 requested changes, later dismissed

2024-10-07 21:12 UTC, 1MarBur1 commented on simple-chat/src/index.html
<img width="216" alt="Снимок экрана 2024-10-08 в 00 02 44" src="https://github.com/user-attachments/assets/dadb918f-d21a-4452-8c1f-ca3cffe72099">

нужно перевернуть иконку файла)

2024-10-07 21:12 UTC, 1MarBur1 commented on simple-chat/src/index.js
> +    }
Нам нужно сохранять не только текст сообщения, как-то нужно понимать кто это сообщение отправил, ведь отображаем по разному. Так же раз ты хочешь отображать картинки, нужно чтобы у сообщения был тип, чтобы мы понимали как его нужно отрисовать) 

Если что реализовывать картинки сейчас - необязательно, но если хочешь - будет круто) Так же дата/время отправления сообщения, сейчас она замокана на текущую.

2024-10-07 21:12 UTC, 1MarBur1 commented on simple-chat/src/index.js
> +const mocks = `
давай моки закинем в localstorage и будем их отрисовывать оттуда)

2024-10-07 21:12 UTC, 1MarBur1 commented on simple-chat/src/index.js
> +const mocks = `
но закинем в messages, просто объектом, не html-доком.

2024-10-07 21:12 UTC, 1MarBur1 commented on simple-chat/src/index.html
если сообщение длинное - появляется горизонтальный скролл

<img width="1440" alt="Снимок экрана 2024-10-08 в 00 10 55" src="https://github.com/user-attachments/assets/978735f0-8aaf-4954-89fb-81572a649241">

2024-10-07 21:33 UTC, Bertruchio commented on simple-chat/src/index.html
![Messanger DEMO](https://github.com/user-attachments/assets/348f6bcb-a1ea-40a1-98ab-5e430ec87ff8)

С иконкой согласен. Просто я пытался по максимуму повторить макет. Креативить что-то своё пока тяжело, т.к. вёрстка пока не мой конёк (но я стараюсь)

2024-10-07 21:35 UTC, Bertruchio commented on simple-chat/src/index.html
А вот что происходит с текстом, пока для меня загадка...

![image](https://github.com/user-attachments/assets/5492d8e0-1d52-4494-a02d-0dd8037eb93d)

2024-10-07 21:42 UTC, Bertruchio commented on simple-chat/src/index.js
> +const mocks = `
Логично. Про то, что моки можно закинуть в локалку, почему-то даже не подумал.

А документ создавал временно, чтобы не прибавлять лишней работы, создавая пример данных из бд (вдруг они уже готовы, а я тут мудрить начал). Мне пока тяжело понять грань того, что необходимо сделать на конкретную домашнюю работу.

2024-10-10 20:16 UTC, 1MarBur1 commented on simple-chat/src/index.html
здесь переноситься по пробелу - если его нет, то верстка едет)

2024-10-27 18:06 UTC, martinkomitsky commented
@Bertruchio привет! будут ли ещё исправления или можно смотреть?

2024-10-27 19:26 UTC, Bertruchio commented
> @Bertruchio привет! будут ли ещё исправления или можно смотреть?

@martinkomitsky, здравствуй! Нет, уже не будет (проект видимо допишу уже потом, для себя)... Неделю назад написал менеджеру, чтобы меня отчислили с курса. Пришлось экстренно приоритеты менять.

P.S.: Прошу прощения за пинг. Забыл удалить проверяющих из проекта. 
P.P.S.: Защищал лабораторную работу по CI/CD, нужна была пересборка проекта. В последнем коммите ничего толком нет, только пару комментариев удаляет. 😂

2024-11-05 07:53 UTC, martinkomitsky commented
> ыл удалить проверяющих из проекта.
> P.P.S.: Защищал лабораторную работу по CI/CD, нужна была пересборка проекта. В последнем коммите ничего толком нет, только пару комментариев удаляет. 😂

Хорошо! Спасибо, что ответил. Успехов тебе и приходи обязательно в следующий раз)

2024-11-05 07:54 UTC, martinkomitsky approved these changes

2024-11-05 07:54 UTC, martinkomitsky commented
12!

2024-11-05 07:54 UTC, merged